### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by LXYrsy** [infinity7428/hANMCL#21]
Why is the result of the new paper much better than that of the previous version?and How to do zero shot inference? thank you!

**Comment by LXYrsy** [comment]
the result of the new paper table1-4 is  after fine-tune? table 5 is zero shot ? it means without fine-tune?thank you!

**Comment by LXYrsy** [comment]
and how to run on pascal voc dataset?

**Comment by Argthx** [comment]
Did you manage to get it running on the Pascal VOC dataset ? If yes, how ? Do you have the correct .json files (test_split1.json and so on) ?

It seems that we dont have the annotation files for Pascal VOC right now, there are indeed .json files on the support link, but there are not the right ones, am i right ?

**Comment by lxylxq001** [comment]
> 您是否设法让它在Pascal VOC数据集上运行？如果是，如何？您是否有正确的 .json 文件（test_split1.json 等）？
> 
> 似乎我们现在没有 Pascal VOC 的注释文件，支持链接上确实有 .json 文件，但没有正确的文件，对吗？

I tried running on the VOC dataset, but it did lack the corresponding JSON file and there were corresponding errors in the code, such as the opposite of the training and prediction JSON files. You need to modify the code. I used a self built JSON file, which includes 5 basic categories and 15 novel categories, and has three types of partitioning.
